# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: producto.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'producto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducto.proto\x12\x08producto\"F\n\x0fProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\"\\\n\x19\x41\x63tualizarProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"\x18\n\nProductoId\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x10ProductoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"?\n\x0eListaProductos\x12-\n\tproductos\x18\x01 \x03(\x0b\x32\x1a.producto.ProductoResponse\"\x07\n\x05Vacio\"\x1e\n\x10\x45liminarResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xf9\x02\n\x0fProductoService\x12\x46\n\rCrearProducto\x12\x19.producto.ProductoRequest\x1a\x1a.producto.ProductoResponse\x12\x43\n\x0fObtenerProducto\x12\x14.producto.ProductoId\x1a\x1a.producto.ProductoResponse\x12<\n\x0fListarProductos\x12\x0f.producto.Vacio\x1a\x18.producto.ListaProductos\x12U\n\x12\x41\x63tualizarProducto\x12#.producto.ActualizarProductoRequest\x1a\x1a.producto.ProductoResponse\x12\x44\n\x10\x45liminarProducto\x12\x14.producto.ProductoId\x1a\x1a.producto.EliminarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOREQUEST']._serialized_start=28
  _globals['_PRODUCTOREQUEST']._serialized_end=98
  _globals['_ACTUALIZARPRODUCTOREQUEST']._serialized_start=100
  _globals['_ACTUALIZARPRODUCTOREQUEST']._serialized_end=192
  _globals['_PRODUCTOID']._serialized_start=194
  _globals['_PRODUCTOID']._serialized_end=218
  _globals['_PRODUCTORESPONSE']._serialized_start=220
  _globals['_PRODUCTORESPONSE']._serialized_end=303
  _globals['_LISTAPRODUCTOS']._serialized_start=305
  _globals['_LISTAPRODUCTOS']._serialized_end=368
  _globals['_VACIO']._serialized_start=370
  _globals['_VACIO']._serialized_end=377
  _globals['_ELIMINARRESPONSE']._serialized_start=379
  _globals['_ELIMINARRESPONSE']._serialized_end=409
  _globals['_PRODUCTOSERVICE']._serialized_start=412
  _globals['_PRODUCTOSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
